FROM python:3.8-slim
WORKDIR /src
COPY ./requirements.txt .
RUN pip install -r ./requirements.txt
COPY . .
#EXPOSE 8080
CMD ["uvicorn", "src.app:app","--proxy-headers", "--host", "0.0.0.0","--port","8000"]